### DISCUSSION TITLE
Set up using Cloudflare tunnel

### DISCUSSION THREAD

**Discussion by yeastie** [karlomikus/bar-assistant#346] [Q&A]
Has anyone set this up using a Cloudflare tunnel?  Grateful if someone has docker compose file and any other config that might be needed. Just struggling to grasp what changes i might need to make based on the examples. Thanks

**Comment by briannelson95** [comment]
Commenting to follow, I've not been able to get this working. Keep getting hit with `Unable to connect to "http://localhost:3000/bar" API server` when navigating to https://[subdomain].[domain].com

**Reply by Borriborri** [reply]
any luck?

**Comment by pumacustom0c** [comment]
I have mine working with Cloudflare tunnels. This is my config (obviously my.domain.com is not real): 

.env file: 
`BASE_URL=https://my.domain.com`

Cloudflare: 
```
Subdomain: my 
Domain: domain 
Type: HTTP
URL: 10.X.X.X:3000 #Make this the local IP address
```

**Reply by Borriborri** [reply]
Hi! I'm unfortunately greeted with: Unable to connect to "http://192.168.0.20:3000/bar" API server. [Learn more](https://docs.barassistant.app/faq/).

**Reply by ForBai** [reply]
same problem for me currently, did you found any solution yet?

**Reply by Borriborri** [reply]
no, I did not :(

**Reply by asheers** [reply]
Has anyone managed to achieve this...   I can access Bar Assistant on the hosting device using my domain name but everywhere else I receive the cannot connect error.

**Reply by ForBai** [reply]
Yep got it setup, took some time but then got it.
# My current setup
As working directory i used /DATA/AppData/bar-assistant-new if you want to use another then please replace it with a directory of your choice.
## Nginx

the nginx.conf in my /DATA/AppData/bar-assistant-new/ path

```
server {
    listen 3000 default_server;
    listen [::]:3000 default_server;
    server_name _;

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    client_max_body_size 100M;

    location /bar/ {
        proxy_pass http://bar-assistant:8080/;
    }

    location /search/ {
        proxy_pass http://meilisearch:7700/;
    }

    location / {
        proxy_pass http://salt-rim:8080/;
    }
}
```

## Docker Compose

And here is the docker-compose.yml you can store that file anywhere you want, also please generate a new meilisearch key and replace "please-generate-your-own-key" with this key. The last part (x-casaos) is only important if you are running casaos, if you are not you can just delete it.

``` yml
name: ravishing_hazel
services:
  bar-assistant:
    cpu_shares: 90
    command: []
    container_name: bar-assistant
    depends_on:
      meilisearch:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 7802M
    environment:
      - ALLOW_REGISTRATION=false
      - APP_URL=https://bar.your-domain.net/bar
      - CACHE_DRIVER=file
      - MEILISEARCH_HOST=https://bar.your-domain.net/search
      - MEILISEARCH_KEY=please-generate-your-own-key
      - SESSION_DRIVER=file
    hostname: bar-assistant
    image: barassistant/server:v5
    labels:
      icon: https://icon.casaos.io/main/all/meilisearch.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/bar-assistant-new/api
        target: /var/www/cocktails/storage/bar-assistant
    ports: []
    devices: []
    cap_add: []
    networks:
      - bar-assistant
    privileged: false
  meilisearch:
    cpu_shares: 90
    command: []
    container_name: meilisearch
    deploy:
      resources:
        limits:
          memory: 7802M
    environment:
      - MEILI_ENV=production
      - MEILI_MASTER_KEY=please-generate-your-own-key
    hostname: meilisearch
    image: getmeili/meilisearch:v1.8
    labels:
      icon: https://icon.casaos.io/main/all/meilisearch.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/bar-assistant-new/meili_data
        target: /meili_data
    ports: []
    devices: []
    cap_add: []
    networks:
      - bar-assistant
    privileged: false
  salt-rim:
    cpu_shares: 90
    command: []
    container_name: salt-rim
    depends_on:
      bar-assistant:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 7802M
    environment:
      - API_URL=https://bar.your-domain.net/bar
      - MEILISEARCH_URL=https://bar.your-domain.net/search
    hostname: salt-rim
    image: barassistant/salt-rim:v4
    labels:
      icon: https://icon.casaos.io/main/all/meilisearch.png
    restart: unless-stopped
    ports: []
    volumes: []
    devices: []
    cap_add: []
    networks:
      - bar-assistant
    privileged: false
  webserver:
    cpu_shares: 90
    command: []
    container_name: webserver
    depends_on:
      bar-assistant:
        condition: service_started
        required: true
      meilisearch:
        condition: service_started
        required: true
      salt-rim:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 7802M
    hostname: webserver
    image: nginx:alpine
    labels:
      icon: https://icon.casaos.io/main/all/meilisearch.png
    ports:
      - target: 3000
        published: "3000"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/bar-assistant-new/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    devices: []
    cap_add: []
    environment: []
    networks:
      - bar-assistant
    privileged: false
networks:
  bar-assistant:
    name: bar-assistant
x-casaos:
  author: self
  category: self
  hostname: bar.your-domain.net
  icon: https://icon.casaos.io/main/all/meilisearch.png
  index: /
  is_uncontrolled: false
  port_map: ""
  scheme: https
  store_app_id: ravishing_hazel
  title:
    custom: bar-assistant
    en_us: meilisearch
```

## Cloudflare

Below is also a graphic for my cloudflare tunnel setup (the red parts are redact info that you have to fill in yourself because it can differ to mine)

![grafik](https://github.com/user-attachments/assets/e0b4de44-e0e2-409e-829c-db044bd80021)

**Reply by damitjimii** [reply]
I realize you likely changed some things for security but nothing it that config listens on port 10380 and as far as I can tell 3000 won’t work either as it doesn’t correctly reference the external subdomain (vault) as the variables are all set to “bar” for the subdomain.

**Reply by ForBai** [reply]
Yea you are right, subdomain normaly is "barassistant" for me and port is set to 3000. I just took a screenshot of the wrong tunnel sry.

**Comment by damitjimii** [comment]
My simplified Cloudflare deployment

```
#Simpified bar-assistant build for portainer and cloudflair
# this assumes you have a basic knowledge of Cloudflare zerotrust and Portainer. 
services:
  meilisearch:
    image: getmeili/meilisearch:v1.12 # Never use latest tag
    container_name: meilisearch
    dns:
      - "1.1.1.1"
      - "10.10.10.10"
    # replace 10.10.10.10 with your local DNS or secondary of choice, do not replace 1.1.1.1 as that is cloudflare
    ports:
      - target: 7700
        published: 3002
        protocol: tcp
    # configure barsearch.example.com on Cloudflare zerotrust tunnel to point to http://<dockerhostIP>:3002        
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_ENV=production
    env_file:
      - stack.env
    restart: unless-stopped
    volumes:
      - ${APPDATA}bar-assist/meilisearch_data:/meili_data

  bar-assistant:
    image: barassistant/server:v5
    container_name: bar-assistant
    dns:
      - "1.1.1.1"
      - "10.10.10.10"
    ports:
      - target: 8080
        published: 3001
        protocol: tcp
    # configure barapi.example.com on Cloudflare zerotrust tunnel to point to http://<dockerhostIP>:3001        
    depends_on:
      - meilisearch
    environment:
      - APP_URL=$API_URL
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=$MEILISEARCH_URL # This needs to be host that can be resolved from inside the MEILISEARCH_URLcontainer.
      - CACHE_DRIVER=file # Change to "file" if not using redis
      - SESSION_DRIVER=file # Change to "file" if not using redis
      - ALLOW_REGISTRATION=true
    env_file:
      - stack.env
    restart: unless-stopped
    volumes:
      - ${APPDATA}bar-assist/data:/var/www/cocktails/storage/bar-assistant

  salt-rim:
    image: barassistant/salt-rim:v4
    container_name: salt-rim
    dns:
      - "1.1.1.1"
      - "10.10.10.10"
    ports:
      - target: 8080
        published: 3000
        protocol: tcp
    # configure bar.example.com on Cloudflare zerotrust tunnel to point to http://<dockerhostIP>:3000
    depends_on:
      - bar-assistant
    environment:
      - API_URL=$API_URL
      - MEILISEARCH_URL=$MEILISEARCH_URL
    env_file:
      - stack.env
    restart: unless-stopped

# Env variables 	
APPDATA='./'  #replace with your local path; useful for uploading/downloading backups, 
#On the docker host>chown -R 33:33 .  after starting the stack
MEILI_MASTER_KEY=Change.me.to.something.long
BASE_URL=https://bar.example.com
MEILISEARCH_URL=https://barsearch.example.com
API_URL=https://barapi.example.com
```
