### DISCUSSION TITLE
Trouble migrating v3 -> v4: Attempt to write to a readonly database

### DISCUSSION THREAD

**Discussion by smugleafdev** [karlomikus/bar-assistant#435] [Q&A] [answered]
The error from the logs:

`production.ERROR: SQLSTATE[HY000]: General error: 8 attempt to write a readonly database (Connection: sqlite, SQL: PRAGMA journal_mode = wal;) {"exception":"[object] (Illuminate\\Database\\QueryException(code: HY000): SQLSTATE[HY000]: General error: 8 attempt to write a readonly database (Connection: sqlite, SQL: PRAGMA journal_mode = wal;) at /var/www/cocktails/vendor/laravel/framework/src/Illuminate/Database/Connection.php:825)`

To the best of my knowledge, I have followed the [migration guide](https://docs.barassistant.app/setup/migrate-to-40/). That it is broken means I probably did something wrong. Relevant portions of compose file below, changes marked with <--

 ```
 bar-assistant:
    image: barassistant/server:v4 <-- was v3, now v4 (SaltRim was v2, now v3)
    container_name: barassistant
    depends_on:
      - meilisearch
      - redis
    environment:
<snip>
      - PUID=13014 <-- new entry for user
      - PGID=13010 <-- new entry for group for user
    ports:
      - 3003:8080 <-- was 3003:3000
    restart: unless-stopped
    volumes:
      - /home/<user>/Documents/docker-bar/data/bar-assistant:/var/www/cocktails/storage/bar-assistant <-- binding, I have chowned the /home/<user>/Documents/.../bar-assistant directory and recursively all files in it to the new user I created at PUID 13014
```

So in order, I have:

1. Since I am using mounts, I created a new user and group, I recursively chowned the directory to that user, and added the user and group to the environment section of the compose file
2. Updated the container power from 3000 to 8080
3. Pulled and ran docker compose
4. Deleted the two env vars, one was under bar-assistant and the other was under salt-rim

Possible mistakes I made:

1. From the migration guide: "you need to make sure that the folder is owned by the user that is running the container, in this case 33:33 (www-data)." I'm not 100% certain I understand that, so I made a new user and put it in the environment.
2. I made no modifications to nginx, as it was already forwarding 3003

Previous versions:

Salt Rim: [v2.18.0](https://github.com/karlomikus/vue-salt-rim/releases)
Bar Assistant: [v3.19.1](https://github.com/karlomikus/bar-assistant/releases)
Meilisearch: [1.7.6](https://github.com/meilisearch/meilisearch/releases)
