### DISCUSSION TITLE
First-time setup- unable to connect to API

### DISCUSSION THREAD

**Discussion by Landrin201** [karlomikus/bar-assistant#450] [Q&A]
Hi! I'm running into a few things here.

First, there's a really annoying bug on the login page I think yall should know about- if you can't connect to the API, the loading overlay gets stuck in place and just blurs out the entire login form, which  obscures any error messages. 

But my real issue is that for some reason, I can't connect to my API. I'm running bar-assistant behind NginxProxyManager at `bar.example.com` (not the real URL, obviously) which is a domain I set up in Cloudflare. I have multiple other services running behind this NGINX instance and I've set this up the same way, so I'm fairly certain that isn't my problem here.

My config files are as follows:

docker-compose:

```
services:
  meilisearch:
    image: getmeili/meilisearch:v1.12 # Never use latest tag
    environment:
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production
    restart: unless-stopped
    volumes:
      - /configStorage/config/bar-assistant/meilisearch_data:/meili_data

  # Optional, but recommended
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped

  bar-assistant:
    image: barassistant/server:v5
    depends_on:
      - meilisearch
      - redis # Remove if not using redis
    environment:
      - APP_URL=$API_URL
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=http://meilisearch:7700 # This needs to be host that can be resolved from inside the container.
      - REDIS_HOST=redis # Remove if not using redis
      - CACHE_DRIVER=redis # Change to "file" if not using redis
      - SESSION_DRIVER=redis # Change to "file" if not using redis
      - ALLOW_REGISTRATION=true
    restart: unless-stopped
    volumes:
      - /storage/bar-assistant/bar_data:/var/www/cocktails/storage/bar-assistant

  salt-rim:
    image: barassistant/salt-rim:v4
    depends_on:
      - bar-assistant
    environment:
      - API_URL=$API_URL
      - MEILISEARCH_URL=$MEILISEARCH_URL

    restart: unless-stopped

  # Reverse proxy all web services
  # API, Salt-Rim and Meilisearch containers must be accesible from your browser
  # You can remove this service if you already have a reverse proxy somewhere in your stack,
  # but you will need to manually setup the configuration
  # Check included nginx.conf for reference
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - bar-assistant
      - salt-rim
      - meilisearch
    ports:
      - 3000:3000
    volumes:
      - /configStorage/config/bar-assistant/nginx.conf:/etc/nginx/conf.d/default.conf
```

Environment variables (I use portainer to do my container management, so I just set up the variables):
```
MEILI_MASTER_KEY: secret
BASE_URL: http://bar.example.com
MEILISEARCH_URL: ${BASE_URL}/search
API_URL: ${BASE_URL}/bar
```

nginx.conf:
```
server {
    listen 3000 default_server;
    listen [::]:3000 default_server;
    server_name _;

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    client_max_body_size 100M;

    location /bar/ {
        proxy_pass http://bar-assistant:8080/;
    }

    location /search/ {
        proxy_pass http://meilisearch:7700/;
    }

    location / {
        proxy_pass http://salt-rim:8080/;
    }
}

server {
    server_name bar.example.com;

    location /bar/ {
        proxy_pass http://bar-assistant:8080/;
    }

    location /search/ {
        proxy_pass http://meilisearch:7700/;
    }

    location / {
        proxy_pass http://salt-rim:8080/;
    }
}
```

And last, a screenshot of my NGINX proxy manager setup (with the ip address obscured)

![Screenshot 2025-03-13 at 11-38-28 Nginx Proxy Manager](https://github.com/user-attachments/assets/c649d509-fc15-44aa-b53c-9461d57336bf)

Now, some things I notice happening with this setup:

1. Going to bar.example.com takes me to the login page
2. Going to bar.example.com/bar/ gives a bad gateway error
3. Going to bar.example.com/search/ redirects to the login page

I'm not sure what's wrong in this setup, I'm hoping someone here will spot it. Thanks!

**Comment by karlomikus** [comment]
Hello.

I'm guessing NginxProxyManager is running as a dedicated reverse proxy.

So if you want to proxy like this:

```mermaid
flowchart LR
    npm[NPM]--> ws[BA webserver service] --> ba[BA services]
```

Then you need to setup your npm to reverse proxy to webserver service. [Looking at the screenshots](https://nginxproxymanager.com/screenshots/proxy-hosts.png), your source should be `bar.example.com` and destination `webserver:3000` (or whatever hostname npm can resolve to webserver container)

**Reply by Landrin201** [reply]
> I'm guessing NginxProxyManager is running as a dedicated reverse proxy.

Correct

> your source should be bar.example.com and destination webserver:3000

Right, I thought that's how I had set this up though? For all my other services, I access them locally by going to ipAddress:port (0.0.0.0:3000 for example) and that's how I set up bar-assistant as well, as in my screenshot in the OP. In the docker-compose I expose port 3000 for the webserver.

I'm not sure what I'm missing here; I don't see anything that seems to be incorrect in my setup. 

If I look in the logs for the webserver, I see the same error every few lines:

`nginx: [emerg] host not found in upstream "bar-assistant" in /etc/nginx/conf.d/default.conf:12`

I just had a thought and changed by setup but it didn't change the outcome; I modified the docker-compose file to the following:

```
services:
  meilisearch:
    image: getmeili/meilisearch:v1.12 # Never use latest tag
    environment:
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production
    ports:
      - 34782:7700
    restart: unless-stopped
    volumes:
      - /configStorage/config/bar-assistant/meilisearch_data:/meili_data

  # Optional, but recommended
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped

  bar-assistant:
    image: barassistant/server:v5
    depends_on:
      - meilisearch
      - redis # Remove if not using redis
    environment:
      - APP_URL=$API_URL
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=http://192.168.1.1:34782 # This needs to be host that can be resolved from inside the container.
      - REDIS_HOST=redis # Remove if not using redis
      - CACHE_DRIVER=redis # Change to "file" if not using redis
      - SESSION_DRIVER=redis # Change to "file" if not using redis
      - ALLOW_REGISTRATION=true
    ports:
      - 34783:8080
    restart: unless-stopped
    volumes:
      - /storage/bar-assistant/bar_data:/var/www/cocktails/storage/bar-assistant

  salt-rim:
    image: barassistant/salt-rim:v4
    depends_on:
      - bar-assistant
    environment:
      - API_URL=$API_URL
      - MEILISEARCH_URL=$MEILISEARCH_URL
    ports:
      - 34784:8080
    restart: unless-stopped

  # Reverse proxy all web services
  # API, Salt-Rim and Meilisearch containers must be accesible from your browser
  # You can remove this service if you already have a reverse proxy somewhere in your stack,
  # but you will need to manually setup the configuration
  # Check included nginx.conf for reference
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - bar-assistant
      - salt-rim
      - meilisearch
    ports:
      - 3000:3000
    volumes:
      - /configStorage/config/bar-assistant/nginx.conf:/etc/nginx/conf.d/default.conf
```

I deliberately exposed the ports for the API, search, and salt-rim containers. That way I can hit them at ipAddr:port like I do with my other services. Then I updated the nginx.conf to the following: 

```
server {
    listen 3000 default_server;
    listen [::]:3000 default_server;
    server_name _;

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    client_max_body_size 100M;

    location /bar/ {
        proxy_pass http://192.168.1.1:34783/;
    }

    location /search/ {
        proxy_pass http://192.168.1.1:34782/;
    }

    location / {
        proxy_pass http://192.168.1.1:34784/;
    }
}

server {
    server_name bar.example.com;

    location /bar/ {
        proxy_pass http://192.168.1.1:34783/;
    }

    location /search/ {
        proxy_pass http://192.168.1.1:34782/;
    }

    location / {
        proxy_pass http://192.168.1.1:34784/;
    }
}

```

Finally, I changed my BASE_URL environment variable to `http://192.168.1.1`

Now, when I navigate to `192.168.1.1:34782` I would expect to see meilisearch confirm that it's running; I do. 

When I go to `192.168.1.1:34783` I would expect to see something telling me the API is running, but I *do not see that.* I just get "unable to connect." The same goes for `http://10.0.1.41:34783/bar/`; I get an `NS_ERROR_CONNECTION_REFUSED` in my log. 

And when I go to `http://10.0.1.41:34784` I get the login page. 

When I navigate to `bar.example.com` now I see the login page, and it's still blurred out, and still tells me it can't connect to the API. Because the login page shows up, I'm reasonably certain that my webserver's nginx routing is working; it is getting traffic from nginxProxyManager then correctly routing it to `http://10.0.1.41:34784`. But for whatever reason the API is still not working. *Something* is clearly wrong with the API, since I can reach the other services correctly hitting their local IPs. I just don't know what, nor how to fix it. 

When I look at the log I DO see that the API starts correctly and is listening on port 8080. the last lines of the log: 

```
 If you enjoy this project, please consider supporting the project: https://github.com/karlomikus/bar-assistant?tab=readme-ov-file#support-and-donations 

[BAR-ASSISTANT] Bar Assistant API ready [listening on port: 8080]

s6-linux-init-maker: fatal: unable to mkdir /run/s6/basedir: No space left on device
```

Now, I am seeing something odd for the bar-assistant API container in Portainer. When I start the service it has a published port of 34783:8080 as I expect. But once the container is fully running, the published port vanishes. I wonder if that's why I'm not able to navigate to `http://10.0.1.41:34783`, maybe Docker isn't maintaining that port mapping for some reason, causing it to fail to route. But that doesn't make any sense, I don't see any reason that would be happening here.
