### DISCUSSION TITLE
bind mount to ./local-folder - getting error when uploading or editing images

### DISCUSSION THREAD

**Discussion by robuck86** [karlomikus/bar-assistant#458] [General]
- Bar Assistant: v5.0.3
- Salt Rim: 4.01
- Browser: chrome

I have bar-assistant running on Docker windows. I changed this line to bind mount to local-folder so I don't lose bar_data, which I've confirmed does create local-folder\bar_data\ - backups/uploads/database.ba3q.sqlite and populates it with pre-loaded images.

```
    volumes:
      - ./local-folder/bar_data:/var/www/cocktails/storage/bar-assistant

```
However, when I attempt to upload new images or edit and save the pre-loaded images I get this error, and the images are broken.

`2025/03/17 16:05:05 [error] 201#201: *196 open() "/var/www/cocktails/public/uploads/cocktails/1/tokyo-mule-recipe-1_1h2nz4.webp" failed (2: No such file or directory), client: 172.23.0.6, server: _, request: "GET /uploads/cocktails/1/tokyo-mule-recipe-1_1h2nz4.webp HTTP/1.0", host: "bar-assistant:8080", referrer: "http://192.168.0.108:3000/cocktails/tokyo-mule-recipe-1";
`

I can see that it created a new image what looks like the correct path : "G:\barassistant\local-folder\bar_data\uploads\cocktails\1\tokyo-mule-recipe-1_1h2nz4.webp"

I also can't run docker compose exec bar-assistant php artisan bar:full-backup - I get this error: [2025-03-17 16:09:11] production.ERROR: ZipArchive::addGlob(): No such file or directory

These issues don't happen when I use the default configuration of

```
     volumes:
      - bar_data:/var/www/cocktails/storage/bar-assistant

```
I'm a beginner with docker. Did I make a mistake in the configuration somewhere?  I'll include my docker compose yml below.

### Additional Context / Logs
```
volumes:
  bar_data:
  meilisearch_data:

services:
  meilisearch:
    image: getmeili/meilisearch:v1.12 # Never use latest tag
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production
    restart: unless-stopped
    volumes:
      - meilisearch_data:/meili_data

  # Optional, but recommended
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped

  bar-assistant:
    image: barassistant/server:v5
    depends_on:
      - meilisearch
      - redis # Remove if not using redis
    environment:
      - APP_URL=$API_URL
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=http://meilisearch:7700 # This needs to be host that can be resolved from inside the container.
      - REDIS_HOST=redis # Remove if not using redis
      - CACHE_DRIVER=redis # Change to "file" if not using redis
      - SESSION_DRIVER=redis # Change to "file" if not using redis
      - ALLOW_REGISTRATION=true
    restart: unless-stopped
    volumes:
      - ./local-folder/bar_data:/var/www/cocktails/storage/bar-assistant

  salt-rim:
    image: barassistant/salt-rim:v4
    depends_on:
      - bar-assistant
    environment:
      - API_URL=$API_URL
      - MEILISEARCH_URL=$MEILISEARCH_URL
    restart: unless-stopped

  # Reverse proxy all web services
  # API, Salt-Rim and Meilisearch containers must be accesible from your browser
  # You can remove this service if you already have a reverse proxy somewhere in your stack,
  # but you will need to manually setup the configuration
  # Check included nginx.conf for reference
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - bar-assistant
      - salt-rim
      - meilisearch
    ports:
      - 3000:3000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
```
