### ISSUE TITLE
Cors issue with webserver

### ISSUE THREAD

**Issue by eskemojoe007** [karlomikus/bar-assistant#106]
- [ x] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
[A clear and concise description of what the bug is.]
Cors error with the default configuration.
```
Errors
Fetch error
NetworkError when attempting to fetch resource. http://bar-assistant:3000/api/server/openapi
Fetch error
Possible cross-origin (CORS) issue? The URL origin (http://bar-assistant:3000) does not match the page (http://<ipaddress>:3000). Check the server returns the correct 'Access-Control-Allow-*' headers.
```

**To Reproduce**
[If possible, steps to reproduce the behavior.]
I followed the documentation to setup with the following docker compose:

```yml
  meilisearch:
    image: getmeili/meilisearch:v1.0
    environment:
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production

    restart: unless-stopped
    volumes:
      - ${USERDIR}/docker/meilisearch:/meili_data
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
  bar-assistant:
    image: barassistant/server:latest
    depends_on:
      - meilisearch
      - redis
    networks:
      - default
    environment:
      - APP_URL=$API_URL
      - LOG_CHANNEL=stderr
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=$MEILISEARCH_URL
      - REDIS_HOST=redis
      - ALLOW_REGISTRATION=true
    restart: unless-stopped
    volumes:
      - ${USERDIR}/docker/barassistant:/var/www/cocktails/storage/bar-assistant

  salt-rim:
    image: barassistant/salt-rim:latest
    depends_on:
      - bar-assistant
    environment:
      - API_URL=$API_URL
      - MEILISEARCH_URL=$MEILISEARCH_URL
      - BAR_NAME=$BAR_NAME
      - DESCRIPTION=$BAR_DESCRIPTION
      - DEFAULT_LOCALE=en-US
    restart: unless-stopped
    networks:
      - default
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 3000:3000 # 
    volumes:
      - ${USERDIR}/docker/bar-webserver/nginx.conf:/etc/nginx/conf.d/default.conf 
```

My files look like:
```env
#.env
# Your Meilisearch master key
# Find out more here: https://docs.meilisearch.com/learn/getting_started/quick_start.html#securing-meilisearch
MEILI_MASTER_KEY=<key>
# Base URL of the application
# You should update this value to the one you are using (ex: http://192.168.100.100, https://my-personal-bar.com)
# In this case it's the URL and port that is exposed in webserver service
# The value MUST be without trailing slash
BASE_URL=http://ipaddress:3000

# Meilisearch server instance URL, change if you are using different host from base url, otherwise leave as default
MEILISEARCH_URL=http://meilisearch:7700

# Bar Assistant server instance URL, change if you are using different host from base url, otherwise leave as default
API_URL=${BASE_URL}/bar

# (Optional) Bar name
BAR_NAME=Cool Bar

# (Optional) Short bar description
BAR_DESCRIPTION=Cool Descrip
```

```conf
#nginx.conf
server {
    listen 3000 default_server;
    listen [::]:3000 default_server;
    server_name _;

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    client_max_body_size 100M;

    location /bar/ {
        proxy_pass http://bar-assistant:3000/;
    }

    location /search/ {
        proxy_pass http://meilisearch:7700/;
    }

    location / {
        proxy_pass http://salt-rim:8080/;
    }
}
```

**Versions:**
 - Docker: 23.0.6, run with `docker version`
 - Browser (if applicable) [e.g. chrome, safari] - All edge and firefox
