### ISSUE TITLE
SQL errors during initial startup, no default user created or data imported

### ISSUE THREAD

**Issue by remus-selea** [karlomikus/bar-assistant#189]
- [x ] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
SQL errors during initial startup, no default user or data being imported.

**To Reproduce**
1. Defined the docker compose as below
2. Created empty bar_data folder and `chown` with the `www-data` user to be allowed to write there.
3. Start up with `docker compose up -d`  

Please check the attached logs file.

```
version: "3"

services:
  meilisearch:
    image: getmeili/meilisearch:v1.1
    container_name: services.bar-assistant-meilisearch
    environment:
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production
    restart: unless-stopped
    volumes:
      - ./meilisearch_data:/meili_data
    networks:
      - bar-network
      - proxy-network

  redis:
    image: redis
    container_name: services.bar-assistant-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    networks:
      - bar-network

  bar-assistant:
    image: barassistant/server:latest
    container_name: services.bar-assistant
    depends_on:
      - meilisearch
      - redis
    environment:
      - APP_URL=$API_URL
      - LOG_CHANNEL=stderr
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=$MEILISEARCH_URL
      - REDIS_HOST=redis
      - ALLOW_REGISTRATION=true
      # - DISABLE_LOGIN=true # Optional if you want to disable auth
    restart: unless-stopped
    volumes:
      - ./bar_data:/var/www/cocktails/storage/bar-assistant
    networks:
        - bar-network
        - proxy-network

  salt-rim:
    image: barassistant/salt-rim:latest
    container_name: services.bar-assistant-salt-rim
    depends_on:
      - bar-assistant
    environment:
      - API_URL=$SALT_RIM_API_URL
      - MEILISEARCH_URL=$MEILISEARCH_URL
      - BAR_NAME=$BAR_NAME
      - DESCRIPTION=$BAR_DESCRIPTION
      - DEFAULT_LOCALE=en-US
      # - DISABLE_LOGIN=true # Optional if you want to disable auth
    restart: unless-stopped
    networks:
      - bar-network
      - proxy-network

  
networks:
  bar-network:
     name: bar-network
  proxy-network:
    external: true
```

Strange behavior afterwards. The first created user cannot be used to log in. Only the second created user seems to be able to log in.

Same issue happens when using volumes instead of directories. e.g.
```
volumes:
  bar_data:
  meilisearch_data:
```

**Versions:**
 - Docker: 23.0.3 

**Additional context, log outputs...**
[_services.bar-assistant_logs.txt](https://github.com/karlomikus/bar-assistant/files/12706770/_services.bar-assistant_logs.txt)
