### ISSUE TITLE
Config for Traefik

### ISSUE THREAD

**Issue by thomas-mc-work** [karlomikus/bar-assistant#330]
Hello @karlomikus,

> I'm successfully using traefik reverse proxy for my instances, so I can maybe help with some config options.

_Originally posted by @karlomikus in https://github.com/karlomikus/bar-assistant/issues/65#issuecomment-1409067762_

Could you please share your config? I didn't manage to get it working. Thank you!

**Comment by thomas-mc-work** [comment]
My approch so far:

    services:       
      bar-assistant:   
        …
        labels:
          traefik.http.routers.ba-bar.rule: Host(`bar-assistant.lan`) && PathPrefix(`/bar`)
      meilisearch:
        …
        labels:
          traefik.http.routers.ba-search.rule: Host(`bar-assistant.lan`) && PathPrefix(`/search`)
      salt-rim:
        …
        labels:
          traefik.http.routers.ba-salt.rule: Host(`bar-assistant.lan`) && PathPrefix(`/`)
          traefik.http.services.ba-salt.loadbalancer.server.port: "8080"

The login page shows up and tells:

> Bar Assistant server:
> http://bar-assistant.lan/bar
> Status: Not available

A query on it gives me this:

    $ curl http://bar-assistant.lan/bar/version
    {"type":"api_error","message":"Resource not found."}

**Comment by karlomikus** [comment]
Hello,
Try adding [strip prefixes middleware](https://doc.traefik.io/traefik/middlewares/http/stripprefix/), this worked for me.

```yaml
volumes:
  bar_data:
  meilisearch_data:

services:
  meilisearch:
    ...
    labels:
      traefik.http.routers.ba-search.rule: Host(`localhost`) && PathPrefix(`/search`)
      traefik.http.middlewares.search-strip.stripprefix.prefixes: /search
      traefik.http.routers.ba-search.middlewares: search-strip

  bar-assistant:
    ...
    labels:
      traefik.http.routers.ba-bar.rule: Host(`localhost`) && PathPrefix(`/bar`)
      traefik.http.middlewares.bar-strip.stripprefix.prefixes: /bar
      traefik.http.routers.ba-bar.middlewares: bar-strip

  salt-rim:
    ...
    labels:
      traefik.http.routers.ba-salt.rule: Host(`localhost`)
      traefik.http.services.ba-salt.loadbalancer.server.port: "8080"

  reverse-proxy:
    image: traefik:v3.1
    command: --api.insecure=true --providers.docker --accesslog=true
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

But I would recommend to expose services as subdomains, so your config will be much simpler.

So for example:

```yaml
# expose meilisearch on `search.bar-assistant.lan`
traefik.http.routers.ba-search.rule: Host(`search.bar-assistant.lan`)

# expose api on `api.bar-assistant.lan`
traefik.http.routers.ba-bar.rule: Host(`api.bar-assistant.lan`)
```

(also don't forget to update your env)

Btw, correct URL for that curl should be: "http://bar-assistant.lan/bar/api/server/version"

Hope this helps.

**Comment by dphildebrandt** [comment]
Why do you need to expose the other services?

In theory, with salt-rim as the client, it should be the only service that needs to be exposed to the internet through the proxy, while bar-assistant, redis and meilisearch could be on a shared network with salt-rim that is internal only, no?

It would make setup simpler (instead of various urls you should be able to just point to the internal services?) and more secure (no need to expose all these services to the web).

**Comment by thomas-mc-work** [comment]
Thank you, @karlomikus! That helped me.

Here is my configuration for anybody finding this issue:

`.env`:

    DOMAIN=bar-assistant.lan
    MEILI_MASTER_KEY=…
    BASE_URL=http://${DOMAIN}
    MEILISEARCH_URL=https://search.${DOMAIN}
    API_URL=http://api.${DOMAIN}

`docker-compose.override.yml`:

    networks:
      bara:
      traefik:
        name: traefik
        external: true

    services:
      meilisearch:
        networks:
          - traefik
          - bara
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-search.rule=Host(`search.${DOMAIN:?}`)"

      redis:
        networks:
          - bara

      bar-assistant:
        networks:
          - bara
          - traefik
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-api.rule=Host(`api.${DOMAIN:?}`)"

      salt-rim:
        networks:
          - traefik
          - bara
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-sr.rule=Host(`${DOMAIN:?}`)"
          # I had to specify this in order to work:
          - "traefik.http.services.${COMPOSE_PROJECT_NAME}-sr.loadbalancer.server.port=8080"

Maybe it's worth to add that into the documentation. The approach using `docker-compose.override.yml` makes it pretty modular.

One final question: is it required to expose the search API publicly? If not then it could be accessed internally using the private network.

**Comment by phillf** [comment]
I am trying to do the same thing with Traefik but am at a loss. meilisearch and bar-assistant 404. 

* The hosts `drink.creativetech.me`, `ba-api.creativetech.me` and `ba-search.creativetech.me` are pointed at Traefik
* DNS resolves to correct IP
* salt-rim is accessible via `http://$IP:8080`with the `Unable to connect to "https://ba-api.creativetech.me" API server. Make sure the server is running and accessible. Check your browser console for more information.`
    * This makes sense given that both api and search 404.

## stack.env
```
DOMAIN=creativetech.me
MEILI_MASTER_KEY=[REDACTED]
BASE_URL=https://drink.${DOMAIN}
MEILISEARCH_URL=https://ba-search.${DOMAIN}
API_URL=https://ba-api.${DOMAIN}
```

## docker-compose.override.yml
```
services:
  meilisearch:
    networks:
      - traefik-backend
      - bar-assistant-backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-search.entrypoints=https
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-search.rule=Host(`ba-search.${DOMAIN:?}`)
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-search.loadbalancer.server.port=7700

  redis:
    networks:
      - bar-assistant-backend

  bar-assistant:
    networks:
      - traefik-backend
      - bar-assistant-backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-api.entrypoints=https
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-api.rule=Host(`ba-api.${DOMAIN:?}`)
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-api.loadbalancer.server.port=8080

  salt-rim:
    networks:
      - traefik-backend
      - bar-assistant-backend
    ports:
      - 8089:8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-sr.entrypoints=https 
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-sr.rule=Host(`drink.${DOMAIN:?}`)
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-sr.loadbalancer.server.port=8080

networks:
  bar-assistant-backend:
    name: bar-assistant-backend
    ipam:
      config:
        - subnet: 172.1.6.0/24 #change subnet as necessary
  traefik-backend:
    external: true
```
