### ISSUE TITLE
Provided hostUrl value (1st parameter) is not a string, expected string

### ISSUE THREAD

**Issue by dlmw** [karlomikus/bar-assistant#345]
- [x] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
When I go to "Menu", click on "Add menu category" and "Add cocktail", the following error appears in the console: "Provided hostUrl value (1st parameter) is not a string, expected string"

However, I have kind of a weird setup, because I use Caddy and had to write the following config file in order to have images correctly displayed:
```
bar.dlmw.ch {
    @uploads {
        path_regexp uploads ^/uploads/(.*)
    }
    rewrite @uploads /bar/uploads/{re.uploads.1}

    handle_path /search/* {
        reverse_proxy meilisearch:7700
    }
    handle_path /bar/* {
        reverse_proxy barassistant:8080
    }
    handle_path /* {
        reverse_proxy saltrim:8080
    }
}
```
It's hard to troubleshoot the issue but I wondered if you had the time to help me. :)

**To Reproduce**
See above.

**Versions:**
 - Bar Assistant: v4.0.2
 - Salt Rim: v3.2.1
 - Browser: Firefox

**Additional context, log outputs...**
[Add any other context about the problem here.]

**Comment by karlomikus** [comment]
This looks like an issue with meilisearch host URL.

Make sure your .env file has correct URL. Can you post what is the output of `window.srConfig` from your salt-rim browser console.

**Comment by dlmw** [comment]
Here's the ouput of `window.srConfig`:
```json
{
  "VERSION": "v3.2.1",
  "API_URL": "https://bar.dlmw.ch/bar",
  "MEILISEARCH_URL": "https://bar.dlmw.ch/search",
  "DEFAULT_LOCALE": "en-US",
  "ENV": "",
  "MAILS_ENABLED": false,
  "BILLING_TOKEN": "",
  "BILLING_ENABLED": false,
  "BILLING_ENV": "",
  "ANALYTICS_HOST": "",
  "ALLOW_REGISTRATION": ""
}
```
And just in case, here's what the environment variables of the server container look like:
```yml
barassistant:
  image: barassistant/server:4.0.2
  depends_on:
    - meilisearch
    - redis
  environment:
    - APP_URL=https://bar.dlmw.ch
    - LOG_CHANNEL=stderr
    - MEILISEARCH_KEY=[REDACTED]
    - MEILISEARCH_HOST=http://meilisearch:7700
```
