### ISSUE TITLE
Recipe images not loading

### ISSUE THREAD

**Issue by NolanBecker** [karlomikus/bar-assistant#429]
- [x] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
Recipe images are not loading when [on the recipe page](https://github.com/user-attachments/assets/597e9d11-871b-4a58-a401-d0a3865a0399). [Thumbnails load just fine](https://github.com/user-attachments/assets/358dc90e-ae98-4267-aab7-6af6e87eba7e) everywhere else. It's the same issue as #312 where the URI is https://bar.mydomain.com/uploads/cocktails/1/tokyo-mule-recipe-1_pkKnx9.webp but should be https://bar.mydomain.com/bar/uploads/1/tokyo-mule-recipe-1_pkKnx9.webp. My setup uses the docker compose with the webserver service and a nginx.conf file. I attempted to add a redirect rule to the nginx file, but haven't been able to get that working either.
Any advice is appreciated, I know I must just be overlooking something.

**To Reproduce**
1. Setup the nginx.conf file as such
```yaml
server {
    listen 3000 default_server;
    listen [::]:3000 default_server;
    server_name _;

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    client_max_body_size 100M;

    location /bar/ {
        proxy_pass http://bar-assistant:8080/;
    }

    location /search/ {
        proxy_pass http://bar-search:7700/;
    }

    location / {
        proxy_pass http://bar-app:8080/;
    }
}
```

**Versions:**
 - Bar Assistant: v4.4.1
 - Salt Rim: v3.9.1
 - Browser: Firefox v135.0

**Additional context, log outputs...**
Docker Compose file:
```yaml
#################### NETWORKS
networks:
  frontend:
    external: true
  backend:
    external: true

#################### SERVICES

services:

  meilisearch:
    image: getmeili/meilisearch:v1.8
    container_name: bar-search
    environment:
      - MEILI_MASTER_KEY=$MEILISEARCH_KEY
      - MEILI_ENV=production
    volumes:
      - /configs/bar-assistant/meilisearch:/meili_data
    restart: unless-stopped
    networks:
      - backend
      - frontend
  
  salt-rim:
    image: barassistant/salt-rim:v3
    container_name: bar-app
    environment:
      - API_URL=https://bar.mydomain.com/bar
      - MEILISEARCH_URL=https://bar.mydomain.com/search
      - BAR_NAME=Bar
      - DESCRIPTION=My bar
      - DEFAULT_LOCALE=en-US
    depends_on:
      - bar-assistant
    restart: unless-stopped
    networks:
      - backend
      - frontend
  
  webserver:
    image: nginx:alpine
    container_name: bar-server
    volumes:
      - /configs/bar-assistant/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - meilisearch
      - salt-rim
      - bar-assistant
    restart: unless-stopped
    networks:
      - backend
      - frontend
  
  bar-assistant:
    image: barassistant/server:v4
    container_name: bar-assistant
    volumes:
      - /configs/bar-assistant/assistant:/var/www/cocktails/storage/bar-assistant
    environment:
      - API_URL=https://bar.mydomain.com/bar
      - MEILISEARCH_KEY=$MEILISEARCH_KEY
      - MEILISEARCH_HOST=http://meilisearch:7700
      - REDIS_HOST=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - ALLOW_REGISTRATION=true
    depends_on:
      - redis
      - meilisearch
    restart: unless-stopped
    networks:
      - backend
      - frontend
  
  redis:
    image: redis
    container_name: bar-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    networks:
      - backend
```
