### ISSUE TITLE
Unable to connect to API server has wrong path

### ISSUE THREAD

**Issue by ctrenthem159** [karlomikus/bar-assistant#441]
- [x] I have read [the FAQ](https://bar-assistant.github.io/docs/faq/).

**Describe the bug**
I am trying to set up BA on my existing infrastructure with Caddy as a reverse proxy. I am consistently getting the "unable to connect to API" message when trying to access the frontpage regardless of what settings I have on the compose file.

I do have another meilisearch instance at version 1.11.1 but that gives me an error about being unable to connect, so I basically have 2 different search containers for 2 different apps.

## Docker Compose (Only relevant parts)

```
    caddy:
        build:
            dockerfile: ./caddy.Dockerfile #custom plugins for other services included in caddy
        container_name: caddy
        restart: unless-stopped
        cap_add: ["NET_ADMIN"]
        ports: ["80:80", "443:443", "443:443/udp"]
        environment:
            - DOMAIN=DOMAINNAME
        volumes:
            - /srv:/srv
            - $PWD/conf:/etc/caddy
            - caddy_data:/data
            - caddy_config:/config
        networks: ["frontend", "bar_backend"]

    meilisearch-bar:
        image: getmeili/meilisearch:v1.8
        container_name: meilisearch-bar
        restart: unless-stopped
        environment:
            - MEILI_NO_ANALYTICS=true
            - MEILIE_ENV=production
            - MEILI_MASTER_KEY=SECRET
        volumes:
            - bar_meili:/meili_data
        networks: ["bar_backend"]

    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        networks: ["bar_backend"]

    bar-assistant:
        image: barassistant/server:v4
        container_name: bar-assistant
        restart: unless-stopped
        environment:
            - APP_URL=https://DOMAIN/api
            - MEILISEARCH_KEY=SECRET
            - MEILISEARCH_HOST=http://meilisearch-bar:7700
            - REDIS_HOST=redis
            - CACHE_DRIVER=redis
            - SESSION_DRIVER=redis
            - ALLOW_REGISTRATION=true
        volumes:
            - bar_data:/var/www/cocktails/storage/bar-assistant
        networks: ["bar_backend"]
        depends_on: ["meilisearch-bar", "redis"]

    salt-rim:
        image: barassistant/salt-rim:v3
        container_name: salt-rim
        restart: unless-stopped
        environment:
            - API_URL=https://DOMAIN/api
            - MEILISEARCH_KEY=SECRET
        networks: ["frontend", "bar_backend"]
        depends_on: ["bar-assistant"]
```

## Caddyfile (only relevant parts)

```
drinks.{$DOMAIN} {
    # I tried bar-assistant:3000 and bar-assistant:8080, it doesn't work either way.
	reverse_proxy /api/* bar-assistant:8080
	reverse_proxy /search/* meilisearch-bar:7700
	reverse_proxy salt-rim:8080
}
```

Result:

![Image](https://github.com/user-attachments/assets/5bc56ef4-ea61-41ed-b6f4-68c5747d9a6b)
