### ISSUE TITLE
Unable to connect to the Meilisearch server at "http://meilisearch:7700". Some features will be missing.

### ISSUE THREAD

**Issue by GeneBO98** [karlomikus/bar-assistant#451]
- [x] I have read [the FAQ](https://docs.barassistant.app/faq/).

**Describe the bug**
I can get the stack up and on the same docker network, but when I access the web interface through the my reverse proxy Caddy, it will say that it cannot connect to http://meilisearch:7700. This does not occur when accessing the portal at http://ip:3000

**To Reproduce**
Access the web page through Caddy reverse proxy. None of the other ports in the stack of containers is exposed, just 3000.

**Versions:**
 - Bar Assistant: v5
 - Salt Rim: v4
 - Browser: Brave

**Additional context, log outputs...**
Not sure if any of the logs are applicable because the containers seem to be running fine.

**Comment by karlomikus** [comment]
Hello, please post your docker-compose.yml and .env file. Web client should try to connect to `/search` and not internal docker hostname.

**Comment by GeneBO98** [comment]
```yaml
volumes:
  bar_data:
  meilisearch_data:

services:
  meilisearch:
    image: getmeili/meilisearch:v1.12 # Never use latest tag
    hostname: meilisearch
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production
    restart: unless-stopped
    ports:
      - 7700:7700
    volumes:
      - meilisearch_data:/meili_data

  # Optional, but recommended
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped

  bar-assistant:
    image: barassistant/server:v5
    depends_on:
      - meilisearch
      - redis # Remove if not using redis
    environment:
      - APP_URL=$API_URL
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=http://192.168.2.24:7700 # This needs to be host that can be resolved from inside the container.
      - REDIS_HOST=redis # Remove if not using redis
      - CACHE_DRIVER=redis # Change to "file" if not using redis
      - SESSION_DRIVER=redis # Change to "file" if not using redis
      - ALLOW_REGISTRATION=true
    restart: unless-stopped
    volumes:
      - bar_data:/var/www/cocktails/storage/bar-assistant

  salt-rim:
    image: barassistant/salt-rim:v4
    depends_on:
      - bar-assistant
    environment:
      - API_URL=$API_URL
      - MEILISEARCH_URL=$MEILISEARCH_URL
    restart: unless-stopped

  # Reverse proxy all web services
  # API, Salt-Rim and Meilisearch containers must be accesible from your browser
  # You can remove this service if you already have a reverse proxy somewhere in your stack,
  # but you will need to manually setup the configuration
  # Check included nginx.conf for reference
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - bar-assistant
      - salt-rim
      - meilisearch
    ports:
      - 3000:3000
    volumes:
      - /home/user/bar-assistant/nginx.conf:/etc/nginx/conf.d/default.conf
```
# Your Meilisearch master key
# Find out more here: https://docs.meilisearch.com/learn/getting_started/quick_start.html#securing-meilisearch
MEILI_MASTER_KEY=secret

# Base URL of the application
# You should update this value to the URL you plan to use (ex: http://192.168.100.100, https://my-personal-bar.com)
# The value MUST be without trailing slash
BASE_URL=http://localhost:3000

# Meilisearch server instance URL, change if you are using different host from base url, otherwise leave as default
# Must be accessible from your browser
MEILISEARCH_URL=${BASE_URL}/search

# Bar Assistant server instance URL, change if you are using different host from base url, otherwise leave as default
# Must be accessible from your browser
API_URL=${BASE_URL}/bar

**Comment by karlomikus** [comment]
This looks fine. Can you post your Caddyfile?

You should just reverse proxy to localhost:3000 and update your BASE_URL to use your new domain.

**Comment by GeneBO98** [comment]
```bash
# Reverse Proxy Domain: "7478e261-04f3-4ad2-a091-a9261f58b01a"
bar.id10tips.com {
        @7ed0b093-b024-4432-acba-549e4182a73b_barid10tipscom {
                not client_ip 192.168.2.0/24 192.168.4.0/24 10.20.50.0/24
        }
        handle @7ed0b093-b024-4432-acba-549e4182a73b_barid10tipscom {
                abort
        }

        handle {
                reverse_proxy 192.168.2.24:3000 {
                }
        }
}
```

**Comment by karlomikus** [comment]
Is there a reason why your `MEILISEARCH_HOST=http://192.168.2.24:7700 # This needs to be host that can be resolved from inside the container.` in docker compose is set to that ip. This looks like container can't resolve that IP.

**Comment by GeneBO98** [comment]
Sorry about that, I was doing testing. Here is the most up to date docker-compose.yaml with the same issue

```yaml
volumes:
  bar_data:
  meilisearch_data:

services:
  meilisearch:
    image: getmeili/meilisearch:v1.12 # Never use latest tag
    hostname: meilisearch
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production
    restart: unless-stopped

    volumes:
      - meilisearch_data:/meili_data

  # Optional, but recommended
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped

  bar-assistant:
    image: barassistant/server:v5
    depends_on:
      - meilisearch
      - redis # Remove if not using redis
    environment:
      - APP_URL=$API_URL
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=http://meilisearch:7700 # This needs to be host that can be resolved from inside the container.
      - REDIS_HOST=redis # Remove if not using redis
      - CACHE_DRIVER=redis # Change to "file" if not using redis
      - SESSION_DRIVER=redis # Change to "file" if not using redis
      - ALLOW_REGISTRATION=true
    restart: unless-stopped
    volumes:
      - bar_data:/var/www/cocktails/storage/bar-assistant

  salt-rim:
    image: barassistant/salt-rim:v4
    depends_on:
      - bar-assistant
    environment:
      - API_URL=$API_URL
      - MEILISEARCH_URL=$MEILISEARCH_URL
    restart: unless-stopped

  # Reverse proxy all web services
  # API, Salt-Rim and Meilisearch containers must be accesible from your browser
  # You can remove this service if you already have a reverse proxy somewhere in your stack,
  # but you will need to manually setup the configuration
  # Check included nginx.conf for reference
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - bar-assistant
      - salt-rim
      - meilisearch
    ports:
      - 3000:3000
    volumes:
      - /home/boverton/bar-assistant/nginx.conf:/etc/nginx/conf.d/default.conf
```
