### ISSUE TITLE
Error when importing via URL or add pictures via URL

### ISSUE THREAD

**Issue by sbreble** [karlomikus/bar-assistant#472]
### Prerequisites
- [ Y] I have searched for [similar issues](https://github.com/karlomikus/bar-assistant/issues).
- [Y ] I have read [the FAQ](https://docs.barassistant.app/faq/).

### Versions
- Bar Assistant: v5
- Salt Rim: v4
- Browser: (if applicable) firefox, edge, chromium on different PCs and networks

### Question
I am unable to import cocktail via URL importer. A Curl error appear on top of the screen (see screenshot attached). 
I am able to manually create a cocktail but I can't add a picture via URL as well. An error saying unable to upload picture (also attached). I can however upload a picture locally stored.
Please any clue to help me fix this issue is greatly appreciated. Or any other logs I should look at.

### Additional Context / Logs
I can't find anything in the logs. Bar Assistant logs only show the initialization logs and salt-rim logs are empty.

One note to add is that I was unable to run docker as current user so I have been using with sudo. Not sure this could have cause a permission issues with the volumes. 
I'm not using redis in the file below but have tried both.

Thank you!!!

Here is my yml file:

```yml
volumes:
  bar_data:
  meilisearch_data:

services:
  meilisearch:
    image: getmeili/meilisearch:v1.12 # Never use latest tag
    container_name: meilisearch
    environment:
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production
    ports:
      - 7700:7700
    restart: unless-stopped
    volumes:
      - meilisearch_data:/meili_data
    env_file:
      - .env

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  bar-assistant:
    image: barassistant/server:v5
    container_name: barassistant
    depends_on:
      meilisearch:
        condition: service_started
      redis:
        condition: service_healthy
    ports:
      - 8080:8080
      - 8443:8443
      - 9000:9000
    environment:
      - APP_URL=$API_URL
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=$MEILI_SERVER          # This needs to be host that can be resolved from inside the container.
      #- REDIS_HOST=redis # Remove if not using redis
      - CACHE_DRIVER=file #redis # Change to "file" if not using redis
      - SESSION_DRIVER=file #redis # Change to "file" if not using redis
      - ALLOW_REGISTRATION=true
      - PARENT_INGREDIENT_SUBSTITUTE=true
      - LOG_CHANNEL=stderr
    restart: unless-stopped
    volumes:
      - bar_data:/var/www/cocktails/storage/bar-assistant
    env_file:
      - .env

  salt-rim:
    image: barassistant/salt-rim:v4
    container_name: salt-rim
    depends_on:
      - bar-assistant
    ports:
      - 8010:8080
    environment:
      - API_URL=$API_URL
      - MEILISEARCH_URL=$MEILISEARCH_URL
    restart: unless-stopped
    env_file:
      - .env
```

![Image](https://github.com/user-attachments/assets/51246fe9-9dbd-4b03-b4ec-c77627d76374)

![Image](https://github.com/user-attachments/assets/381b042b-9a70-40f9-8554-b80779881c35)

`
