### ISSUE TITLE
Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80

### ISSUE THREAD

**Issue by Akirainblack** [karlomikus/bar-assistant#50]
My docker compose snippet for bar assistant:
```
  bar-assistant:
    image: kmikus12/bar-assistant-server:v1.0.4
    container_name: bar-assistant
    depends_on:
      - meilisearch
      - meili-redis
    environment:
      - APP_URL=http://<IP Address>:8900
      - MEILISEARCH_KEY=<$MEILI_MASTER_KEY>
      - MEILISEARCH_HOST=http://<IP Adddress>:7700
      - REDIS_HOST=redis
    restart: unless-stopped
    volumes:
      - /volume2/docker/bar/ba:/var/www/cocktails/storage
    ports:
      - 8900:80
```
Log:
```
AH00015: Unable to open logs
Updating search index settings...
Syncing cocktails and ingredients to meilisearch...
Adding routes and config to cache...
   INFO  Configuration cached successfully.  
   INFO  Routes cached successfully.  
Application ready!
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
```
Please can you advise where I've gone wrong? Tried both 1.0.5 and 1.0.4

**Comment by karlomikus** [comment]
Possibly related to #12 

Try switching to named volumes, change the following:

```
- /volume2/docker/bar/ba:/var/www/cocktails/storage
```

to 
``` yaml
- ba-storage:/var/www/cocktails/storage
```

And add the following at the end of the file
```
volumes:
  ba-storage:
```

You can refrence the following compose file: https://github.com/bar-assistant/docker/blob/master/docker-compose.yml

**Comment by Akirainblack** [comment]
That's not the problem.. The container is running so all folder mappings are there and happy. It's not able to bind port 80.

**Comment by karlomikus** [comment]
Since this is not your whole compose file, do you have only bar assistant services in it or any other. Maybe something else is already listening on the port 80.

**Comment by Akirainblack** [comment]
As per the ports section of my compose:
    ports:
      - 8900:80
      It shouldn't be trying to bind to port 80

**Comment by zhdenny** [comment]
If I remember, I might have had this exact same problem until I did what the developer suggests regarding using named storages. Did you actually try that? I know it doesn't sound related, but give it a shot.

**Comment by Akirainblack** [comment]
Tried this, however no different. 
:(

**Comment by Akirainblack** [comment]
Had to add:
    user: 0:0
 
before it would work. Not happy with it as a solution though as that's now running as root.

**Comment by karlomikus** [comment]
Yeah, that should not be needed to run.
On what hardware are you running this? I have an instance on my RPI3, desktop PCs and a server and everything is working fine.

**Comment by Akirainblack** [comment]
A synology NAS. DS918+ to be precise
Of note with everything as it stands in my compose it works perfectly, builds the database, imports the ingredients etc all the way up until it tries to bind the port as per the original log above. It only works from there on if I add "user: 0:0" to the compose.

**Comment by Akirainblack** [comment]
Any update on this, please?

**Comment by karlomikus** [comment]
I can't do much without successfully recreating that error locally.

Can you share your minimal docker compose file that creates this error.

**Comment by Akirainblack** [comment]
version: "3"

services:
  # Setup Meilisearch instance
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v0.29
    environment:
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production
    restart: unless-stopped
    ports:
      - 7700:7700
    volumes:
      - /volume2/docker/bar/meili:/meili_data
    networks:
      - bar
  # Redis for session and file cache
  meili-redis:
    image: redis
    container_name: meili-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    networks:
      - bar
  # Bar Assistant API
  bar-assistant:
    image: kmikus12/bar-assistant-server
    container_name: bar-assistant
    user: 0:0
    depends_on:
      - meilisearch
      - meili-redis
    environment:
      - APP_URL=$BAR_URL
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=$MEILI_HOST
      - REDIS_HOST=redis
      - ALLOW_REGISTRATION=false
    restart: unless-stopped
    volumes:
      - /volume2/docker/bar/ba:/var/www/cocktails/storage
    ports:
      - 8900:80
    networks:
      - bar
  # Bar Assistant Client
  salt-rim:
    image: kmikus12/salt-rim
    container_name: salt-rim
    depends_on:
      - meilisearch
      - bar-assistant
    environment:
      - API_URL=$API_URL
    restart: unless-stopped
    ports:
      - 8980:8080
    networks:
      - bar
##NETWORKS
networks:
    bar:
        external: true

**Comment by karlomikus** [comment]
Here's my modified version of your compose file that works for me:

``` yaml
version: "3"

services:
  # Setup Meilisearch instance
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v0.29
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_ENV=production
    restart: unless-stopped
    ports:
      - 7778:7700
    volumes:
      - ./meili:/meili_data
    networks:
      - bar
  # Redis for session and file cache
  meili-redis:
    image: redis
    container_name: meili-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    networks:
      - bar
  # Bar Assistant API
  bar-assistant:
    image: kmikus12/bar-assistant-server
    container_name: bar-assistant
    # user: 0:0
    depends_on:
      - meilisearch
      - meili-redis
    environment:
      - APP_URL=http://localhost:8900
      - MEILISEARCH_KEY=masterKey
      - MEILISEARCH_HOST=http://localhost:7778
      - REDIS_HOST=redis
      - ALLOW_REGISTRATION=false
    restart: unless-stopped
    volumes:
      - ./ba:/var/www/cocktails/storage
    ports:
      - 8900:80
    networks:
      - bar
  # Bar Assistant Client
  salt-rim:
    image: kmikus12/salt-rim
    container_name: salt-rim
    depends_on:
      - meilisearch
      - bar-assistant
    environment:
      - API_URL=http://localhost:8900
    restart: unless-stopped
    ports:
      - 8980:8080
    networks:
      - bar
##NETWORKS
networks:
  bar:
    external: true
```

You probably have some specific server configuration, like maybe you are running docker in rootless mode, but you need root privileges to bind port 80.
I'm not sure, but you don't have to necessarily use `user: 0:0`, you could create a new user that is in a docker group and use his GID and UID.
Otherwise I can't help you much, you could maybe test it on another hardware or on your local pc and see if it works there.
