### ISSUE TITLE
docker example will not connect between containers

### ISSUE THREAD

**Issue by kavemang** [karlomikus/bar-assistant#62]
[https://github.com/bar-assistant/docker](https://github.com/bar-assistant/docker)

when spinning up the example compose the first issue is that the api server cannot see meilisearch 

```
In CurlResponse.php line 327:
                                                                               
  Failed to connect to localhost port 7700: Connection refused for "http://lo  
  calhost:7700/indexes/cocktails/settings".
```

started making some modifications and experimenting here: https://github.com/karlomikus/bar-assistant/issues/60#issuecomment-1407478273

**Comment by zhdenny** [comment]
This is my docker compose which works for me.

```
version: "3"

services:
  meilisearch:
    image: getmeili/meilisearch
    environment:
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production
    restart: unless-stopped
    ports:
      - 7700:7700
    volumes:
      - ba-meilidata:/meili_data

  # Redis for session and file cache
  redis2:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped

  bar-assistant:
    image: kmikus12/bar-assistant-server
    depends_on:
      - meilisearch
    environment:
      - APP_URL=$API_URL
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=$MEILI_HOST
      - REDIS_HOST=redis2
    restart: unless-stopped
    volumes:
      - ba-storage:/var/www/cocktails/storage
    ports:
      - 8000:80

  salt-rim:
    image: kmikus12/salt-rim
    depends_on:
      - meilisearch
      - bar-assistant
    environment:
      - API_URL=$API_URL
    ports:
      - 8083:8080

volumes:
  ba-meilidata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/user/appdata/meilisearch
  ba-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/user/appdata/ba-storage
```

**Comment by JzJad** [comment]
Depending on the docker/compose version localhost may not work. Specify the container name and use that instead.

compose

`services:
  # Setup Meilisearch instance
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v0.29`

.env

`API_URL=http://bar-assistant:8000
MEILI_HOST=http://meilisearch:7700`

**Comment by kavemang** [comment]
@zhdenny using your compose and premade volumes I got everything seeming to be connected with container names

no particular errors on any of the containers and I can see the server is connected to redis, but when I try to log in on salt I still get "failed to fetch"

**Comment by karlomikus** [comment]
You need to have access to your BA instance from your browser. So when you are finished setting up your container you should be able to visit your BA and meilisearch instance.

For the given example of https://github.com/bar-assistant/docker , if you visit `localhost:8000` you should see your BA instance, and if you visit `localhost:7700` you should see your meilisearch instance.

**Comment by JamesTeague** [comment]
I've got a similar issue. I can hit the BA instance from the browser but it returns a 500 Internal Server Error from the console.

**Comment by karlomikus** [comment]
Can you check your container logs when you try to login

```bash
$ docker compose logs bar-assistant
```

**Comment by JamesTeague** [comment]
Here is the full log after hitting the BA instance endpoint.

```[Sun Jan 29 10:09:53.981642 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) PHP/8.1.14 configured -- resuming normal operations
[Sun Jan 29 10:09:53.981674 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
Application .env file not found, creating a new .env file...

   INFO  Application key set successfully.  


   INFO  The [public/storage] link has been connected to [storage/app/public].  

   INFO  The [public/uploads] link has been connected to [storage/uploads].  

Database already exists, running migrations...

   INFO  Nothing to migrate.  

Updating search index settings...
Syncing cocktails and ingredients to meilisearch...
Adding routes and config to cache...

   INFO  Configuration cached successfully.  


   INFO  Routes cached successfully.  

Application ready!
localhost:80 192.168.86.8 - - [29/Jan/2023:12:32:12 -0600] "GET / HTTP/1.1" 500 211 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0"
localhost:80 192.168.86.8 - - [29/Jan/2023:12:32:13 -0600] "GET /favicon.ico HTTP/1.1" 200 296 "http://192.168.86.4:8888/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0"
```

It shows that I have hit the backend but nothing of note to my eye and I just get a blank white page.

**Comment by JamesTeague** [comment]
It is worth noting that I have installed this on Unraid but in this case I'm not sure that would cause issue. It still is just running the container.

**Comment by zhdenny** [comment]
I'm on Unraid as well. Not sure why yours is not working.
For what it's worth....all the URLs in my .env file are local URLs (192.168.1.111:7700 and 192.168.1.111:8000). That IP is the local IP of my Unraid server.

**Comment by JamesTeague** [comment]
Your APP_URL env does it have a protocol in it? Or just local IP and port?

Do you have an unraid template?

**Comment by kavemang** [comment]
To add to this, i see the same issue as james in my non unraid setup

As well i tried using LAN ips during my attempts

**Comment by zhdenny** [comment]
You must use Docker Compose, not the standard Unraid docker method...so there won't be any Unraid Template. I use the Unraid docker compose plugin in order to install apps which require compose 

http://192.168.1.111:7700
http://192.168.1.111:8000

**Comment by zhdenny** [comment]
I'm on vacation but when I get back in a week I'll try to fire up a second instance of this whole thing from scratch just to make sure. Maybe it works for me just cuz I've had this setup from the beginning months ago. Dunno.

**Comment by wouterverduin** [comment]
> This is my docker compose which works for me.
> 
> ```
> version: "3"
> 
> services:
>   meilisearch:
>     image: getmeili/meilisearch
>     environment:
>       - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
>       - MEILI_ENV=production
>     restart: unless-stopped
>     ports:
>       - 7700:7700
>     volumes:
>       - ba-meilidata:/meili_data
> 
>   # Redis for session and file cache
>   redis2:
>     image: redis
>     environment:
>       - ALLOW_EMPTY_PASSWORD=yes
>     restart: unless-stopped
> 
>   bar-assistant:
>     image: kmikus12/bar-assistant-server
>     depends_on:
>       - meilisearch
>     environment:
>       - APP_URL=$API_URL
>       - MEILISEARCH_KEY=$MEILI_MASTER_KEY
>       - MEILISEARCH_HOST=$MEILI_HOST
>       - REDIS_HOST=redis2
>     restart: unless-stopped
>     volumes:
>       - ba-storage:/var/www/cocktails/storage
>     ports:
>       - 8000:80
> 
>   salt-rim:
>     image: kmikus12/salt-rim
>     depends_on:
>       - meilisearch
>       - bar-assistant
>     environment:
>       - API_URL=$API_URL
>     ports:
>       - 8083:8080
> 
> volumes:
>   ba-meilidata:
>     driver: local
>     driver_opts:
>       type: none
>       o: bind
>       device: /mnt/user/appdata/meilisearch
>   ba-storage:
>     driver: local
>     driver_opts:
>       type: none
>       o: bind
>       device: /mnt/user/appdata/ba-storage
> ```

Running into similar issues. Running on ubuntu and using docker compose. Also tried the above mentioned docker-compose without succes.

Tried different methods (http://localhost:8000, http://192.168.1.161:8000, http://bar-assistant:800) without succes both in the docker-compose and in the .env. All containers seem to be up weirdly enough.

So at a loss of getting this going which i would love to!

Any tips are welcome :)

**Comment by karlomikus** [comment]
Can you post your docker compose file and .env variables.

Also you can check docker logs for errors.

**Comment by wouterverduin** [comment]
Oke; I think i narrowed down the issue to the following:

Problem seems to exist in the bar-assistant instance. In my docker-compose it seems to get the variables from the .env file. However it says two things i cant seem to resolve:

1) Application .env file not found, creating a new .env file...
2) Database not found, creating a new database...
touch: cannot touch '/var/www/cocktails/storage/database.sqlite': Permission denied

When i check the folder i assigned as a volume; It shows a folder for meilisearch as expected but NOTHING for the barassistant container.

I guess if it CAN write the problem is resolved. Dont know why it doesnt write tough...

**Comment by JamesTeague** [comment]
I did not realize that you must use `docker compose`. That may not work for me at the moment but that is good information to know.

**Comment by kavemang** [comment]
@wouterverduin @karlomikus @JamesTeague 

In case this helps at all, I continue to have the exact same issues you guys are describing but I've already tried using an .env file and also tried (alternatively) plugging everything possible in manually with no .env file at all

**Comment by kavemang** [comment]
@wouterverduin @karlomikus @JamesTeague

In case this helps at all, I continue to have the exact same issues you guys are describing but I've already tried using an .env file and also tried (alternatively) plugging everything possible in manually with no .env file at all

**Comment by zhdenny** [comment]
Typically, chained containers like docker compose. That's what I used to get it working on Unraid.

**Comment by karlomikus** [comment]
- Logs with message `Application .env file not found, creating a new .env file...` are related to BA .env file inside the container, it creates a new one if it doesn't exist, and that file is not persisted. That's not the issue.
- There is currently an issue #12 where you can't use local volume paths, you must used named volumes instead. So configuration like: `- /home/wouter/docker/GLOBAL/barassistant/meili:/meili_data` wont work.
- You don't need to use docker compose, you could also run every service manually. If you do that, you should first create an meilisearch instance, then redis, then BA and finally salt-rim

Hope that helps

**Comment by wouterverduin** [comment]
@karlomikus @JamesTeague @kavemang 

I think i got it sorted with karlomikus hints. The problem is in the docker volume mount pmerissions problem he linked. 
I finally got it working; Seeing other cocktails. Can addingredients so it looks like a go!

For references what i finally used to get it up:

first make a .env file:

`API_URL=http://192.168.1.161:8000
MEILI_HOST=http://192.168.1.161:7700
MEILI_MASTER_KEY=something`

Then my docker-compose:

`version: "3"

services:
  # Setup Meilisearch instance
  meilisearch:
    image: getmeili/meilisearch:v0.29
    container_name: bar_meili
    environment:
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production
    restart: unless-stopped
    ports:
      - 7700:7700
    volumes:
      - bar-meilidata:/meili_data
  # Redis for session and file cache
  redis:
    image: redis
    container_name: bar_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
  # Bar Assistant API. Bestanden in : /home/wouter/docker/bar/files
  bar-assistant:
    image: kmikus12/bar-assistant-server
    container_name: bar_assistant
    depends_on:
      - meilisearch
      - redis
    environment:
      - APP_URL=$API_URL
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=$MEILI_HOST
      - REDIS_HOST=redis
    restart: unless-stopped
    volumes:
      - bar-storage:/var/www/cocktails/storage
    ports:
      - 8000:80
  # Bar Assistant Client
  salt-rim:
    image: kmikus12/salt-rim
    container_name: bar_salt
    depends_on:
      - meilisearch
      - bar-assistant
    environment:
      - API_URL=$API_URL
    restart: unless-stopped
    ports:
      - 8090:8080

volumes:
   bar-storage:
   bar-meilidata:`

**Comment by JamesTeague** [comment]
I'm still getting 500 errors when hitting the API even when using docker compose following the documentation. I am not sure where that is coming from or what is happening. It is not showing up in the logs at all.

**Comment by karlomikus** [comment]
This looks like you didn't setup .env correctly when making the container. Try stopping and removing the container and running it again. Or post your docker-compose.yml and .env you are using

**Comment by JamesTeague** [comment]
docker-compose.yml
```
version: "3"

services:
  # Setup Meilisearch instance
  meilisearch:
    image: getmeili/meilisearch:v0.29
    environment:
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production
    restart: unless-stopped
    ports:
      - 7700:7700
    volumes:
      - ba-meilidata:/meili_data

  # Bar Assistant API
  bar-assistant:
    image: kmikus12/bar-assistant-server
    depends_on:
      - meilisearch
    environment:
      - APP_URL=$API_URL
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=$MEILI_HOST
      - REDIS_HOST=$REDIS_HOST
    restart: unless-stopped
    volumes:
      - ba-storage:/var/www/cocktails/storage
    ports:
      - 8888:80

  # Bar Assistant Client
  salt-rim:
    image: kmikus12/salt-rim
    depends_on:
      - meilisearch
      - bar-assistant
    environment:
      - API_URL=$API_URL
    restart: unless-stopped
    ports:
      - 8980:8080

volumes:
  ba-meilidata:
  ba-storage:
```

.env
```
API_URL=http://192.168.86.4:8888
MEILI_HOST=http://192.168.86.4:7700
MEILI_MASTER_KEY=someMasterKeyForNow
REDIS_HOST=http://192.168.86.4:6379
```
