### ISSUE TITLE
Error When Trying to Login (JSON)

### ISSUE THREAD

**Issue by beboprocky** [karlomikus/bar-assistant#63]
Attempt to login or register results in the following error:
JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

A red box with this message appears on top of the Salt Rim login page. Using docker-compose on a Linux server, Ubuntu 22.04LTS. 

Here is my docker-compose file:

```
#version: "3"

services:
  # Setup Meilisearch instance
  meilisearch:
    image: getmeili/meilisearch:v0.29
    environment:
      - MEILI_MASTER_KEY=$MEILI_MASTER_KEY
      - MEILI_ENV=production
    restart: unless-stopped
    ports:
      - 7700:7700
    volumes:
      - ba-meilidata:/meili_data

  # Redis for session and file cache
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped

  # Bar Assistant API
  bar-assistant:
    image: kmikus12/bar-assistant-server
    depends_on:
      - meilisearch
      - redis
    environment:
      - APP_URL=$API_URL
      - MEILISEARCH_KEY=$MEILI_MASTER_KEY
      - MEILISEARCH_HOST=$MEILI_HOST
      - REDIS_HOST=redis
    restart: unless-stopped
    volumes:
      - ba-storage:/var/www/cocktails/storage
    ports:
      - 8001:80

  # Bar Assistant Client
  salt-rim:
    image: kmikus12/salt-rim
    depends_on:
      - meilisearch
      - bar-assistant
    environment:
      - API_URL=$API_URL
    restart: unless-stopped
    ports:
      - 12005:8080

volumes:
  ba-meilidata:
  ba-storage:
```
